all: cks scheduler eds
cks: CkSchedule.c
	gcc CkSchedule.c -lcurses -o CkSchedule
eds: EdSchedule.c
	gcc EdSchedule.c -lcurses -o EdSchedule
scheduler: scheduler.c
	gcc scheduler.c -lcurses -o scheduler
	
